### ISSUE TITLE
Blink detecting.

### ISSUE THREAD

**Issue by DoubleBoba** [orgicus/Mindwave#1]
How can i give a blink event from your library? I know that android version have that functional.

**Comment by orgicus** [comment]
Unfortunately this may not be possible on the Arduino alone (ThinkGear Serial Stream API).
You will need to use the ThinkGear Communications Driver (TGCD) 

Here are the details from the [Serial Stream API Docs](http://developer.neurosky.com/docs/doku.php?id=thinkgear_communications_protocol#eye_blink_strength):

> Eye Blink Strength
> 
> This data value is currently unavailable via the ThinkGear Serial Stream APIs. It is not directly available as output from any current ThinkGear hardware. For TGCD, see the TG_DATA_BLINK_STRENGTH data type for use with the TG_GetValueStatus() and TG_GetValue() functions.

What this boils down to is using their libraries (c/c++/c#/java) on a computer
